// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO: Replace these with your actual values from Supabase Dashboard → Settings → API
const SUPABASE_URL = "https://ufpcrpapqluwfyyfmtus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcGNycGFwcWx1d2Z5eWZtdHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzEyOTksImV4cCI6MjA3MTYwNzI5OX0.86msSLKf0SL-X9AsDznmXRQRmrdffoCwdYuI44TPzJA"; // Paste your anon key here between the quotes

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});